### ISSUE TITLE
PREFIX looks wrong

### ISSUE THREAD

**Issue by vinriviere** [freemint/gemma#3]
https://github.com/freemint/gemma/blob/12872e4deb31c74798ffb03a3fa5bdab0785b3ce/CONFIGVARS#L35-L36

As `/usr` is always appended to computed `PREFIX`, it will never be empty (unless overriden), so test next line will always fail. This is more likely a bug.

**Comment by th-otto** [comment]
Was only a fallback and should not occur with our toolchains, but still wrong. Fixed in https://github.com/freemint/gemma/commit/a288930b698db77111f4e1fdc94c22af4bf243d3.

**Comment by vinriviere** [comment]
On my Cygwin setup with GCC 4.6.4, `m68k-atari-mint-gcc -print-sysroot` displays nothing.
